"""initial schema

Revision ID: 6abc529a4b8a
Revises: 
Create Date: 2026-07-07 22:26:54.399194
"""

from alembic import op
import sqlalchemy as sa


revision = '6abc529a4b8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=False),
    sa.Column('genres', sa.Text(), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('cover_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_normalized_title'), 'series', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_series_status'), 'series', ['status'], unique=False)
    op.create_index(op.f('ix_series_title'), 'series', ['title'], unique=False)
    op.create_table('source_health',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('best_source', sa.String(length=50), nullable=False),
    sa.Column('downloaded_source', sa.String(length=50), nullable=False),
    sa.Column('cbz_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'number', name='uq_series_chapter')
    )
    op.create_index(op.f('ix_chapter_number'), 'chapter', ['number'], unique=False)
    op.create_index(op.f('ix_chapter_series_id'), 'chapter', ['series_id'], unique=False)
    op.create_table('source_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('genres', sa.Text(), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('cover_path', sa.Text(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_source_series')
    )
    op.create_index(op.f('ix_source_series_normalized_title'), 'source_series', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_source_series_series_id'), 'source_series', ['series_id'], unique=False)
    op.create_index(op.f('ix_source_series_source'), 'source_series', ['source'], unique=False)
    op.create_index(op.f('ix_source_series_source_id'), 'source_series', ['source_id'], unique=False)
    op.create_table('chapter_release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('source_series_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('downloadable_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['source_series_id'], ['source_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_series_id', 'number', name='uq_source_chapter')
    )
    op.create_index(op.f('ix_chapter_release_chapter_id'), 'chapter_release', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_release_number'), 'chapter_release', ['number'], unique=False)
    op.create_index(op.f('ix_chapter_release_source'), 'chapter_release', ['source'], unique=False)
    op.create_index(op.f('ix_chapter_release_source_series_id'), 'chapter_release', ['source_series_id'], unique=False)
    op.create_table('manual_match_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_series_id', sa.Integer(), nullable=False),
    sa.Column('target_series_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_series_id'], ['source_series.id'], ),
    sa.ForeignKeyConstraint(['target_series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_match_rule_source_series_id'), 'manual_match_rule', ['source_series_id'], unique=False)
    op.create_table('match_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_series_id', sa.Integer(), nullable=False),
    sa.Column('candidate_series_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['source_series_id'], ['source_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_series_id', 'candidate_series_id', name='uq_match_candidate')
    )
    op.create_index(op.f('ix_match_candidate_candidate_series_id'), 'match_candidate', ['candidate_series_id'], unique=False)
    op.create_index(op.f('ix_match_candidate_source_series_id'), 'match_candidate', ['source_series_id'], unique=False)
    op.create_index(op.f('ix_match_candidate_status'), 'match_candidate', ['status'], unique=False)
    op.create_table('download_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_release_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_release_id'], ['chapter_release.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_release_id', name='uq_download_job_chapter_release')
    )
    op.create_index(op.f('ix_download_job_chapter_release_id'), 'download_job', ['chapter_release_id'], unique=False)
    op.create_index(op.f('ix_download_job_status'), 'download_job', ['status'], unique=False)
    op.create_table('downloaded_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_release_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['chapter_release_id'], ['chapter_release.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloaded_file_active'), 'downloaded_file', ['active'], unique=False)
    op.create_index(op.f('ix_downloaded_file_chapter_id'), 'downloaded_file', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_downloaded_file_chapter_release_id'), 'downloaded_file', ['chapter_release_id'], unique=False)
    op.create_index(op.f('ix_downloaded_file_source'), 'downloaded_file', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloaded_file_source'), table_name='downloaded_file')
    op.drop_index(op.f('ix_downloaded_file_chapter_release_id'), table_name='downloaded_file')
    op.drop_index(op.f('ix_downloaded_file_chapter_id'), table_name='downloaded_file')
    op.drop_index(op.f('ix_downloaded_file_active'), table_name='downloaded_file')
    op.drop_table('downloaded_file')
    op.drop_index(op.f('ix_download_job_status'), table_name='download_job')
    op.drop_index(op.f('ix_download_job_chapter_release_id'), table_name='download_job')
    op.drop_table('download_job')
    op.drop_index(op.f('ix_match_candidate_status'), table_name='match_candidate')
    op.drop_index(op.f('ix_match_candidate_source_series_id'), table_name='match_candidate')
    op.drop_index(op.f('ix_match_candidate_candidate_series_id'), table_name='match_candidate')
    op.drop_table('match_candidate')
    op.drop_index(op.f('ix_manual_match_rule_source_series_id'), table_name='manual_match_rule')
    op.drop_table('manual_match_rule')
    op.drop_index(op.f('ix_chapter_release_source_series_id'), table_name='chapter_release')
    op.drop_index(op.f('ix_chapter_release_source'), table_name='chapter_release')
    op.drop_index(op.f('ix_chapter_release_number'), table_name='chapter_release')
    op.drop_index(op.f('ix_chapter_release_chapter_id'), table_name='chapter_release')
    op.drop_table('chapter_release')
    op.drop_index(op.f('ix_source_series_source_id'), table_name='source_series')
    op.drop_index(op.f('ix_source_series_source'), table_name='source_series')
    op.drop_index(op.f('ix_source_series_series_id'), table_name='source_series')
    op.drop_index(op.f('ix_source_series_normalized_title'), table_name='source_series')
    op.drop_table('source_series')
    op.drop_index(op.f('ix_chapter_series_id'), table_name='chapter')
    op.drop_index(op.f('ix_chapter_number'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_series_title'), table_name='series')
    op.drop_index(op.f('ix_series_status'), table_name='series')
    op.drop_index(op.f('ix_series_normalized_title'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
