import {Suspense, createContext, lazy, useContext, useEffect, useRef, useState, type ReactNode} from 'react'
import {useInfiniteQuery, useMutation, useQuery, useQueryClient} from '@tanstack/react-query'
import {Activity, AlertTriangle, BookOpen, Check, ChevronDown, ChevronRight, CirclePause, Clock3, Database, Download, ExternalLink, Grid2X2, Heart, History, Library, List, Menu, Merge, Play, RefreshCw, Search, Server, Settings, X, type LucideIcon} from 'lucide-react'
import {NavLink, Route, Routes, useLocation, useNavigate, useSearchParams} from 'react-router-dom'
import {api} from './api'
import type {ActivityEvent, Job, JobGroup, Series, UpdateSeries} from './types'

const MatchesWorkspace=lazy(()=>import('./MatchesWorkspace').then(module=>({default:module.MatchesWorkspace})))

type Toast={id:number;message:string;tone?:'normal'|'error';action?:()=>void;actionLabel?:string}
const ToastContext=createContext<(toast:Omit<Toast,'id'>)=>void>(()=>{})
const fallbackSources=['asura','mangafire','kingofshojo']
const states=['interested','reading','caught_up','paused']

export function App(){
  const [drawer,setDrawer]=useState(false),[toasts,setToasts]=useState<Toast[]>([])
  const queryClient=useQueryClient()
  const operations=useQuery({queryKey:['operations'],queryFn:({signal})=>api.operations(signal),refetchInterval:30_000})
  useEffect(()=>{let last=Number(sessionStorage.getItem('eventCursor')||0);const stream=new EventSource(`/api/v2/events${last?`?after=${last}`:''}`);stream.addEventListener('job',event=>{last=Math.max(last,Number((event as MessageEvent).lastEventId||0));sessionStorage.setItem('eventCursor',String(last));let payload:{kind?:string;type?:string;state?:string}={};try{payload=JSON.parse((event as MessageEvent).data)}catch{}queryClient.invalidateQueries({queryKey:['jobs']});queryClient.invalidateQueries({queryKey:['job-groups']});queryClient.invalidateQueries({queryKey:['job-group-children']});if(payload.type!=='progress'){queryClient.invalidateQueries({queryKey:['workload-cycle']});queryClient.invalidateQueries({queryKey:['operations']});queryClient.invalidateQueries({queryKey:['activity']})}if(payload.kind==='kavita_sync'&&['succeeded','failed','cancelled'].includes(payload.state||'')){queryClient.invalidateQueries({queryKey:['library']});queryClient.invalidateQueries({queryKey:['updates']})}});stream.addEventListener('counts',()=>{queryClient.invalidateQueries({queryKey:['operations']});queryClient.invalidateQueries({queryKey:['workload-cycle']})});return()=>stream.close()},[queryClient])
  useEffect(()=>{document.documentElement.classList.toggle('drawer-open',drawer);return()=>document.documentElement.classList.remove('drawer-open')},[drawer])
  const push=(toast:Omit<Toast,'id'>)=>{const id=Date.now()+Math.random();setToasts(current=>[...current,{...toast,id}]);setTimeout(()=>setToasts(current=>current.filter(item=>item.id!==id)),6500)}
  const active=(operations.data?.job_counts.queued||0)+(operations.data?.job_counts.leased||0)+(operations.data?.job_counts.retry_wait||0)
  const failed=operations.data?.job_counts.failed||0
  return <ToastContext.Provider value={push}><div className="app-shell"><Sidebar/><Topbar active={active} failed={failed} onJobs={()=>setDrawer(true)}/><main className="workspace"><Routes><Route path="/" element={<Discovery/>}/><Route path="/discovery" element={<Discovery/>}/><Route path="/library" element={<LibraryPage/>}/><Route path="/updates" element={<Updates/>}/><Route path="/matches" element={<Suspense fallback={<SkeletonGrid/>}><MatchesWorkspace/></Suspense>}/><Route path="/activity" element={<ActivityPage/>}/><Route path="/operations" element={<Operations/>}/></Routes></main><BottomNav/>{drawer&&<JobDrawer onClose={()=>setDrawer(false)}/>}<div className="toast-stack" role="status">{toasts.map(toast=><div key={toast.id} className={`toast ${toast.tone==='error'?'toast-error':''}`}><span>{toast.message}</span>{toast.action&&<button className="text-button" onClick={toast.action}>{toast.actionLabel}</button>}</div>)}</div></div></ToastContext.Provider>
}

function Sidebar(){return <aside className="side-nav"><NavLink className="brand" to="/discovery"><BookOpen/> <span>Manga Manager</span></NavLink><nav>{[[Search,'Discover','/discovery'],[Library,'Library','/library'],[History,'Updates','/updates'],[Merge,'Matches','/matches'],[Activity,'Activity','/activity'],[Settings,'Operations','/operations']].map(([Icon,label,path])=><NavLink key={path as string} to={path as string}><Icon size={19}/><span>{label as string}</span></NavLink>)}</nav><div className="nav-foot"><span className="health-dot"/> PostgreSQL v2</div></aside>}
function BottomNav(){return <nav className="bottom-nav">{[[Search,'Discover','/discovery'],[Library,'Library','/library'],[History,'Updates','/updates'],[Settings,'Ops','/operations']].map(([Icon,label,path])=><NavLink key={path as string} to={path as string}><Icon size={20}/><span>{label as string}</span></NavLink>)}</nav>}
function Topbar({active,failed,onJobs}:{active:number;failed:number;onJobs:()=>void}){const location=useLocation();const operations=useQuery({queryKey:['operations'],queryFn:({signal})=>api.operations(signal)});const groups=operations.data?.active_groups||0;const labels:Record<string,string>={'/discovery':'Discover','/library':'Library','/updates':'Updates','/matches':'Matches','/activity':'Activity','/operations':'Operations','/':'Discover'};return <header className="top-bar"><div><span className="eyebrow">Manga Manager</span><strong>{labels[location.pathname]||'Manga Manager'}</strong></div><button className="jobs-trigger" onClick={onJobs} aria-label={`Open job center: ${groups} active groups, ${active} active tasks, ${failed} failed`}><span className={`live-pulse ${active?'active':''}`}/><span><b>{groups}</b> groups · {active} tasks</span>{failed>0&&<span className="failed-count"><AlertTriangle size={15}/>{failed}</span>}</button></header>}

function PageHeader({title,subtitle,actions}:{title:string;subtitle:string;actions?:ReactNode}){return <header className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{(actions||title==='Operations')&&<div className="header-actions">{title==='Operations'&&<KavitaAction/>}{actions}</div>}</header>}
function KavitaAction(){const toast=useContext(ToastContext),client=useQueryClient();const sync=useMutation({mutationFn:api.syncKavita,onSuccess:data=>{toast({message:`Queued ${data.created} pending Kavita sync jobs`});client.invalidateQueries({queryKey:['jobs']})},onError:error=>toast({message:error.message,tone:'error'})});return <button className="secondary" disabled={sync.isPending} onClick={()=>sync.mutate()}><RefreshCw/>{sync.isPending?'Queueing…':'Sync pending to Kavita'}</button>}
function Cover({series,className=''}:{series:Pick<Series,'title'|'cover_url'>;className?:string}){const [failed,setFailed]=useState(false);return <div className={`cover ${className}`}>{series.cover_url&&!failed?<img src={series.cover_url} alt={`Cover for ${series.title}`} loading="lazy" onError={()=>setFailed(true)}/>:<div className="cover-placeholder"><BookOpen/><span>Cover unavailable</span></div>}</div>}
function SourceChips({selected,onChange}:{selected:string[];onChange:(value:string[])=>void}){const providers=useQuery({queryKey:['providers'],queryFn:({signal})=>api.providers(signal),staleTime:300_000});const sources=providers.data?.items?.length?providers.data.items:fallbackSources;return <div className="chip-group" aria-label="Filter by source">{sources.map(source=><button key={source} className={`filter-chip ${selected.includes(source)?'selected':''}`} aria-pressed={selected.includes(source)} onClick={()=>onChange(selected.includes(source)?selected.filter(x=>x!==source):[...selected,source])}>{selected.includes(source)&&<Check size={14}/>} {source}</button>)}</div>}
function StatusPill({value}:{value:string}){return <span className={`status-pill status-${value}`}>{value.replace('_',' ')}</span>}
function ErrorState({error}:{error:unknown}){return <div className="empty-state"><AlertTriangle/><h2>Something went wrong</h2><p>{error instanceof Error?error.message:'The request could not be completed.'}</p></div>}
function SkeletonGrid(){return <div className="media-grid">{Array.from({length:8}).map((_,i)=><div className="series-card skeleton" key={i}><div className="skeleton-cover"/><div className="skeleton-line"/><div className="skeleton-line short"/></div>)}</div>}
function useDebounced<T>(value:T,delay=250){const [result,setResult]=useState(value);useEffect(()=>{const timer=setTimeout(()=>setResult(value),delay);return()=>clearTimeout(timer)},[value,delay]);return result}
function AutoPager({hasNext,loading,load,label='Load more'}:{hasNext:boolean;loading:boolean;load:()=>void;label?:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const node=ref.current;if(!node||!hasNext)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting&&!loading)load()},{rootMargin:'700px'});observer.observe(node);return()=>observer.disconnect()},[hasNext,loading,load]);if(!hasNext)return null;return <div ref={ref} className="auto-pager"><button className="load-more" disabled={loading} onClick={load}>{loading?'Loading…':label}</button></div>}

function Discovery(){
  const [searchParams,setSearchParams]=useSearchParams();const initial=searchParams.get('q')||'';const [query,setQuery]=useState(initial);const [selected,setSelected]=useState(()=>searchParams.getAll('source'));const debounced=useDebounced(query);const client=useQueryClient();const toast=useContext(ToastContext)
  useEffect(()=>{const p=new URLSearchParams();if(debounced)p.set('q',debounced);selected.forEach(s=>p.append('source',s));setSearchParams(p,{replace:true})},[debounced,selected.join('|')])
  const result=useInfiniteQuery({queryKey:['discovery',debounced,selected],queryFn:({pageParam,signal})=>api.discovery(debounced,selected,pageParam,signal),initialPageParam:'',getNextPageParam:last=>last.next_cursor||undefined,maxPages:10})
  const track=useMutation({mutationFn:({id,status}:{id:number;status:string})=>api.changeSeries(id,status),onMutate:async({id})=>{await client.cancelQueries({queryKey:['discovery']});const snapshots=client.getQueriesData({queryKey:['discovery']});client.setQueriesData({queryKey:['discovery']},(old:any)=>old?{...old,pages:old.pages.map((page:any)=>({...page,items:page.items.filter((item:Series)=>item.id!==id)}))}:old);return{snapshots}},onError:(error,_variables,context)=>{context?.snapshots.forEach(([key,data])=>client.setQueryData(key,data));toast({message:error.message,tone:'error'})},onSuccess:({item})=>{client.invalidateQueries({queryKey:['library']});toast({message:`${item.title} added to your library`,actionLabel:'Undo',action:()=>api.changeSeries(item.id,'untracked').then(()=>{client.invalidateQueries({queryKey:['discovery']});client.invalidateQueries({queryKey:['library']})})})}})
  const setSources=(values:string[])=>setSelected(values)
  const items=result.data?.pages.flatMap(page=>page.items)||[]
  return <><PageHeader title="Discover" subtitle="Find your next series across every connected source."/><section className="filter-bar"><label className="search-field"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles, aliases, or descriptions…" aria-label="Search catalog"/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={17}/></button>}</label><SourceChips selected={selected} onChange={setSources}/></section>{result.isLoading?<SkeletonGrid/>:result.isError?<ErrorState error={result.error}/>:items.length?<><div className="media-grid discovery-grid">{items.map(series=><DiscoveryCard key={series.id} series={series} onTrack={()=>track.mutate({id:series.id,status:'interested'})}/>)}</div><AutoPager hasNext={!!result.hasNextPage} loading={result.isFetchingNextPage} load={()=>result.fetchNextPage()} label="Load more manga"/></>:<div className="empty-state"><Search/><h2>No manga found</h2><p>Try another phrase or broaden the selected sources.</p></div>}</>
}
function DiscoveryCard({series,onTrack}:{series:Series;onTrack:()=>void}){return <article className="series-card discovery-card"><Cover series={series}/><div className="card-content"><div className="card-heading"><h2>{series.title}</h2><StatusPill value={series.status}/></div><p className="description">{series.description||'No description is available for this series yet.'}</p><div className="source-row">{series.sources.map(source=><a key={source.name} href={source.url} target="_blank" rel="noreferrer">{source.name}<ExternalLink size={12}/></a>)}</div><div className="card-meta"><span><History size={15}/> Latest {series.latest_chapter||'unknown'}</span>{series.latest_at&&<time>{relativeTime(series.latest_at)}</time>}</div><button className="primary wide" onClick={onTrack}><Heart size={17}/> Track manga</button></div></article>}

function LibraryPage(){
  const [paramsState,setParams]=useSearchParams();const [query,setQuery]=useState(paramsState.get('q')||'');const selectedSources=paramsState.getAll('source');const selectedStates=paramsState.getAll('state');const [view,setView]=useState(localStorage.getItem('libraryView')||'grid');const debounced=useDebounced(query)
  const [presets,setPresets]=useState<{name:string;query:string}[]>(()=>JSON.parse(localStorage.getItem('libraryFilters')||'[]'))
  useEffect(()=>{const p=new URLSearchParams();if(debounced)p.set('q',debounced);selectedSources.forEach(x=>p.append('source',x));selectedStates.forEach(x=>p.append('state',x));setParams(p,{replace:true})},[debounced,selectedSources.join('|'),selectedStates.join('|')])
  const result=useInfiniteQuery({queryKey:['library',debounced,selectedSources,selectedStates],queryFn:({pageParam,signal})=>api.library(debounced,selectedSources,selectedStates,pageParam,signal),initialPageParam:'',getNextPageParam:last=>last.next_cursor||undefined,maxPages:10})
  const updateMulti=(key:string,values:string[])=>{const p=new URLSearchParams(paramsState);p.delete(key);values.forEach(v=>p.append(key,v));setParams(p)};const items=result.data?.pages.flatMap(p=>p.items)||[]
  const savePreset=()=>{const name=window.prompt('Name this filter');if(!name)return;const next=[...presets.filter(p=>p.name!==name),{name,query:paramsState.toString()}];setPresets(next);localStorage.setItem('libraryFilters',JSON.stringify(next))}
  return <><PageHeader title="Your library" subtitle="Everything you follow, with reading progress at a glance." actions={<div className="view-toggle"><button className={view==='grid'?'active':''} onClick={()=>{setView('grid');localStorage.setItem('libraryView','grid')}}><Grid2X2 size={17}/> Grid</button><button className={view==='list'?'active':''} onClick={()=>{setView('list');localStorage.setItem('libraryView','list')}}><List size={17}/> List</button></div>}/><section className="filter-stack"><label className="search-field"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your library…"/></label><SourceChips selected={selectedSources} onChange={v=>updateMulti('source',v)}/><div className="chip-group">{states.map(state=><button key={state} className={`filter-chip ${selectedStates.includes(state)?'selected':''}`} onClick={()=>updateMulti('state',selectedStates.includes(state)?selectedStates.filter(x=>x!==state):[...selectedStates,state])}>{state.replace('_',' ')}</button>)}</div><div className="preset-row"><button className="secondary" onClick={savePreset}>Save filter</button>{presets.map(p=><button className="filter-chip" key={p.name} onClick={()=>setParams(new URLSearchParams(p.query))}>{p.name}</button>)}</div></section>{result.isLoading?<SkeletonGrid/>:result.isError?<ErrorState error={result.error}/>:items.length?<><div className={view==='grid'?'library-grid':'library-list'}>{items.map(item=><LibraryCard key={item.id} series={item} view={view}/>)}</div><AutoPager hasNext={!!result.hasNextPage} loading={result.isFetchingNextPage} load={()=>result.fetchNextPage()}/></>:<div className="empty-state"><Library/><h2>Your filtered library is empty</h2><p>Track manga from Discover or clear some filters.</p></div>}</>
}
function LibraryCard({series,view}:{series:Series;view:string}){const client=useQueryClient(),toast=useContext(ToastContext);const mutation=useMutation({mutationFn:(status:string)=>api.changeSeries(series.id,status),onSuccess:({item})=>{client.invalidateQueries({queryKey:['library']});client.invalidateQueries({queryKey:['discovery']});toast({message:`${item.title} is now ${item.status.replace('_',' ')}`})},onError:error=>toast({message:error.message,tone:'error'})});const progress=series.chapter_count?Math.round(series.read_count/series.chapter_count*100):0;return <article className={`library-card ${view==='list'?'compact':''}`}><Cover series={series}/><div className="library-main"><div className="card-heading"><h2>{series.title}</h2><StatusPill value={series.status}/></div><p className="description">{series.description||'No description available.'}</p><div className="source-row">{series.sources.map(s=><span key={s.name}>{s.name}</span>)}</div><div className="progress-head"><span>{series.read_count} of {series.chapter_count} chapters read</span><b>{progress}%</b></div><div className="progress-track"><span style={{width:`${progress}%`}}/></div><div className="library-stats"><span><History size={15}/> Latest {series.latest_chapter||'unknown'}</span><span><BookOpen size={15}/> {series.unread_count} unread</span>{series.integrity_state!=='healthy'&&<span className="warning"><AlertTriangle size={15}/>{series.integrity_state}</span>}</div></div><div className="library-actions"><label>Status<select value={series.status} onChange={e=>mutation.mutate(e.target.value)}>{states.map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}<option value="untracked">untracked</option></select></label></div></article>}

function Updates(){
  const query=useInfiniteQuery({
    queryKey:['updates'],
    queryFn:({pageParam,signal})=>api.updates(pageParam,signal),
    initialPageParam:'',
    getNextPageParam:last=>last.next_cursor||undefined,
    maxPages:10,
  })
  const items=query.data?.pages.flatMap(p=>p.items)||[]
  return <><PageHeader title="Updates" subtitle="Unread releases from manga you track, grouped by series."/>{query.isLoading?<SkeletonGrid/>:query.isError?<ErrorState error={query.error}/>:items.length?<><div className="updates-grid">{items.map(item=><UpdateCard key={item.id} item={item}/>)}</div><AutoPager hasNext={!!query.hasNextPage} loading={query.isFetchingNextPage} load={()=>query.fetchNextPage()} label="Older updates"/></>:<div className="empty-state"><Check/><h2>You’re all caught up</h2><p>New chapters from tracked manga will appear here.</p></div>}</>
}
function UpdateCard({item}:{item:UpdateSeries}){const [expanded,setExpanded]=useState(false);const client=useQueryClient(),toast=useContext(ToastContext);const mark=useMutation({mutationFn:(id:number)=>api.changeChapter(id,'read'),onSuccess:()=>client.invalidateQueries({queryKey:['updates']}),onError:error=>toast({message:error.message,tone:'error'})});const all=useMutation({mutationFn:()=>api.readAll(item.id),onSuccess:()=>{client.invalidateQueries({queryKey:['updates']});client.invalidateQueries({queryKey:['library']});toast({message:`Marked ${item.title} as read`})}});const chapters=expanded?item.unread_chapters:item.unread_chapters.slice(0,1);const toggle=(target:EventTarget|null)=>{if(target instanceof Element&&target.closest('a,button,input,select'))return;setExpanded(value=>!value)};return <article className={`update-card-new ${expanded?'expanded':''}`} role="button" tabIndex={0} aria-expanded={expanded} onClick={event=>toggle(event.target)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setExpanded(value=>!value)}}}><Cover series={item}/><div className="update-main"><div className="card-heading update-sticky"><div><span className="eyebrow">{item.unread_chapters.length} unread</span><h2>{item.title}</h2></div><div className="update-head-actions">{expanded&&<button className="secondary" onClick={()=>setExpanded(false)}><ChevronDown/>Collapse</button>}<button className="icon-button" onClick={()=>all.mutate()} title="Mark all read"><Check/></button></div></div><div className="chapter-stack">{chapters.map(chapter=><div className="chapter-item" key={chapter.id}><a href={chapter.url} target="_blank" rel="noreferrer"><b>Chapter {chapter.number}</b><span>{chapter.source} · {relativeTime(chapter.released_at)}</span></a><button onClick={()=>mark.mutate(chapter.id)}>Mark read</button></div>)}</div>{item.unread_chapters.length>1&&!expanded&&<button className="expand-button" onClick={()=>setExpanded(true)}><ChevronRight/>Show {item.unread_chapters.length-1} more unread</button>}</div></article>}


function ActivityPage(){
  const [status,setStatus]=useState<string[]>([])
  const query=useInfiniteQuery({
    queryKey:['activity',status],
    queryFn:({pageParam,signal})=>api.activity(status,[],pageParam,signal),
    initialPageParam:0,
    getNextPageParam:last=>last.next_cursor||undefined,
    maxPages:10,
  })
  const events=query.data?.pages.flatMap(p=>p.items)||[]
  const grouped=groupEvents(events)
  return <><PageHeader title="Activity" subtitle="A contextual timeline of work performed by the service."/><div className="chip-group section-filter">{['failed','retry_scheduled','succeeded','leased'].map(s=><button key={s} className={`filter-chip ${status.includes(s)?'selected':''}`} onClick={()=>setStatus(status.includes(s)?status.filter(x=>x!==s):[...status,s])}>{s.replace('_',' ')}</button>)}</div>{query.isLoading?<div className="panel-loading"/>:query.isError?<ErrorState error={query.error}/>:<><div className="timeline-new">{grouped.map(group=><ActivityRow key={group.event.id} event={group.event} count={group.count}/>)}</div><AutoPager hasNext={!!query.hasNextPage} loading={query.isFetchingNextPage} load={()=>query.fetchNextPage()} label="Load older activity"/></>}</>
}
function ActivityRow({event,count}:{event:ActivityEvent;count:number}){const [open,setOpen]=useState(false);const bad=event.status==='failed'||event.type==='failed';return <article className={`activity-card ${bad?'bad':''}`}><div className="activity-icon">{bad?<AlertTriangle/>:event.status==='succeeded'?<Check/>:event.status==='leased'?<Play/>:<Clock3/>}</div><div className="activity-content"><div className="activity-title"><h2>{event.job.description}</h2>{count>1&&<span className="repeat-badge">Repeated {count}×</span>}<StatusPill value={event.status}/></div><p>{event.message||humanEvent(event.type)}</p><div className="activity-meta"><span>{event.job.source||event.job.pool}</span><time>{formatDate(event.created_at)}</time><span>Job #{event.job.id}</span></div>{(event.job.error_message||Object.keys(event.details).length>0)&&<><button className="details-toggle" onClick={()=>setOpen(!open)}>{open?<ChevronDown/>:<ChevronRight/>}Technical details</button>{open&&<pre>{event.job.error_message||JSON.stringify(event.details,null,2)}</pre>}</>}</div></article>}

function Operations(){
  const query=useQuery({queryKey:['operations'],queryFn:({signal})=>api.operations(signal),refetchInterval:30_000}),activeJobs=useQuery({queryKey:['jobs','operations','active'],queryFn:({signal})=>api.jobs(['queued','leased','retry_wait'],undefined,100,signal)}),failedJobs=useQuery({queryKey:['jobs','operations','failed'],queryFn:({signal})=>api.jobs(['failed'],undefined,100,signal)}),completedJobs=useQuery({queryKey:['jobs','operations','completed'],queryFn:({signal})=>api.jobs(['succeeded','cancelled'],undefined,100,signal)}),toast=useContext(ToastContext),client=useQueryClient()
  const act=useMutation({mutationFn:({type,value}:{type:string;value?:string})=>type==='pull'?api.pullSource(value!):api.probe(),onSuccess:()=>{toast({message:'Operation queued'});client.invalidateQueries({queryKey:['jobs']})},onError:error=>toast({message:error.message,tone:'error'})})
  if(query.isLoading)return <SkeletonGrid/>;if(query.isError)return <ErrorState error={query.error}/>
  const data=query.data!,active=activeJobs.data?.items||[],failed=failedJobs.data?.items||[],completed=completedJobs.data?.items||[];const metrics:[string,number,LucideIcon][]=[['Active jobs',(data.job_counts.queued||0)+(data.job_counts.leased||0)+(data.job_counts.retry_wait||0),Play],['Failed',data.job_counts.failed||0,AlertTriangle],['Series',data.health.series,Library],['Chapters',data.health.chapters,BookOpen],['Artifacts',data.health.active_artifacts,Download],['Missing',data.health.missing_projections,Database],[data.health.storage_paused?'Storage paused':'Storage ready',Math.round((data.health.storage_free_bytes||0)/1073741824),Database]]
  return <><PageHeader title="Operations" subtitle="Source, worker, queue, storage, and database health in one workspace." actions={<button className="primary" onClick={()=>act.mutate({type:'probe'})}><Activity/>Run health probe</button>}/><section className="metric-grid">{metrics.map(([label,value,Icon])=><article className="metric-card" key={label}><Icon/><div><b>{value}</b><span>{label}</span></div></article>)}</section><section className="operations-section"><div className="section-heading"><div><h2>Sources</h2><p>Polling health, learned capacity, and cooldown state.</p></div></div><div className="source-health-grid">{data.sources.map(source=>{const policy=data.provider_policies.find(p=>p.source===source.source);return <article className="source-health" key={source.source}><div className="source-health-head"><div><span className={`health-indicator ${source.status}`}/><h3>{source.source}</h3></div><StatusPill value={source.status}/></div><dl><div><dt>Last pull</dt><dd>{source.last_poll_at?relativeTime(source.last_poll_at):'Never'}</dd></div><div><dt>Failures</dt><dd>{source.failures}</dd></div><div><dt>Learned limit</dt><dd>{policy?`${policy.job_limit} jobs / ${policy.page_limit} pages`:'Collecting data'}</dd></div><div><dt>Cooldown</dt><dd>{policy?`${policy.cooldown_seconds}s`:'Default'}</dd></div></dl>{source.last_error&&<p className="source-error" title={source.last_error}>{source.last_error}</p>}<button className="secondary wide" onClick={()=>act.mutate({type:'pull',value:source.source})}><RefreshCw/>Pull now</button></article>})}</div></section><section className="operations-section"><div className="section-heading"><div><h2>Workers and permits</h2><p>{data.workers.length} active workers · {Object.values(data.permits).reduce((a,b)=>a+b,0)} permits leased</p></div></div><div className="worker-grid">{data.workers.map(worker=><article className="worker-card" key={worker.id}><Server/><div><h3>{worker.id}</h3><p>{worker.status} · seen {relativeTime(worker.heartbeat_at)}</p>{worker.active_job_id&&<span>Running job #{worker.active_job_id}</span>}</div></article>)}</div></section><JobSection title="Queued and running" subtitle="Work currently moving through the service." jobs={active}/><JobSection title="Failed jobs" subtitle="Work that needs attention or an explicit retry." jobs={failed}/><JobSection title="Recently completed" subtitle="Successful and cancelled terminal work." jobs={completed}/></>
}
function JobSection({title,subtitle,jobs}:{title:string;subtitle:string;jobs:Job[]}){return <section className="operations-section"><div className="section-heading"><div><h2>{title}</h2><p>{subtitle}</p></div><span className="count-badge">{jobs.length}</span></div>{jobs.length?<JobTable jobs={jobs}/>:<div className="empty-inline">No jobs in this section.</div>}</section>}

function JobDrawer({onClose}:{onClose:()=>void}){
  const [tab,setTab]=useState('active')
  const stateMap:Record<string,string[]>={active:['queued','leased','retry_wait'],queued:['queued'],running:['leased'],retry:['retry_wait'],failed:['failed'],recent:['succeeded','cancelled']}
  const states=stateMap[tab]
  const query=useInfiniteQuery({queryKey:['job-groups',tab],queryFn:({pageParam,signal})=>api.jobGroups(states,pageParam,signal),initialPageParam:'',getNextPageParam:last=>last.next_cursor||undefined,refetchInterval:20_000,maxPages:10})
  const cycle=useQuery({queryKey:['workload-cycle'],queryFn:({signal})=>api.workloadCycle(signal),refetchInterval:20_000})
  const items=query.data?.pages.flatMap(page=>page.items)||[]
  return <><div className="drawer-scrim" onClick={onClose}/><aside className="job-drawer" aria-label="Job center"><header><div><span className="eyebrow">Live operations</span><h2>Job center</h2></div><button className="icon-button" onClick={onClose} aria-label="Close jobs"><X/></button></header>{cycle.data&&<CycleProgress cycle={cycle.data}/>}<nav className="drawer-tabs">{Object.keys(stateMap).map(key=><button className={tab===key?'active':''} key={key} onClick={()=>setTab(key)}>{key}</button>)}</nav><div className="drawer-body">{query.isLoading?<div className="panel-loading"/>:query.isError?<ErrorState error={query.error}/>:items.length?<>{items.map(group=><JobGroupCard group={group} states={states} key={group.key}/>) }<AutoPager hasNext={!!query.hasNextPage} loading={query.isFetchingNextPage} load={()=>query.fetchNextPage()} label="Load more job groups"/></>:<div className="empty-state compact"><Check/><h3>No {tab} jobs</h3></div>}</div></aside></>
}
function CycleProgress({cycle}:{cycle:{total:number;successful:number;failed:number;cancelled:number;superseded:number;remaining:number;added:number}}){const settled=cycle.successful+cycle.failed+cycle.cancelled+cycle.superseded;const calculated=cycle.total?Math.min(100,Math.round(settled*100/cycle.total)):100;const percent=cycle.remaining?Math.min(99,calculated):calculated;const summary=cycle.remaining?`${cycle.remaining} of ${cycle.total} tasks left`:`All ${cycle.total} tasks settled`;return <section className="cycle-progress"><div><b>Overall workload</b><span>{summary}</span></div><div className="progress-track" role="progressbar" aria-valuemin={0} aria-valuemax={cycle.total} aria-valuenow={Math.min(settled,cycle.total)}><span style={{width:`${percent}%`}}/></div><div className="cycle-legend"><span>{percent}% settled</span><span>{cycle.successful} completed</span>{cycle.superseded>0&&<span>{cycle.superseded} duplicates removed</span>}{cycle.failed>0&&<span className="danger-text">{cycle.failed} failed</span>}{cycle.cancelled>0&&<span>{cycle.cancelled} cancelled</span>}</div></section>}
function JobGroupCard({group,states}:{group:JobGroup;states:string[]}){
  const [open,setOpen]=useState(false)
  const children=useInfiniteQuery({queryKey:['job-group-children',group.key,states],queryFn:({pageParam,signal})=>api.jobGroupChildren(group.key,states,pageParam,signal),initialPageParam:'',getNextPageParam:last=>last.next_cursor||undefined,enabled:open&&!group.single,maxPages:10})
  if(group.single)return <JobCard job={group.representative}/>
  return <article className="job-group-card"><button className="job-group-head" onClick={()=>setOpen(!open)}>{group.cover_url&&<img src={group.cover_url} alt=""/>}<div><h3>{group.title}</h3><span>{group.task_count} tasks · {Object.entries(group.status_counts).map(([key,value])=>`${value} ${key.replace('_',' ')}`).join(' · ')}</span></div>{open?<ChevronDown/>:<ChevronRight/>}</button><div className="job-progress"><div><span>{group.progress.current} of {group.progress.total} complete</span><b>{group.progress.percent===null?'Planning…':`${group.progress.percent}%`}</b></div><GroupProgressBar group={group}/></div>{open&&<div className="job-group-children">{children.data?.pages.flatMap(page=>page.items).map(job=><JobCard job={job} key={job.id}/>) }<AutoPager hasNext={!!children.hasNextPage} loading={children.isFetchingNextPage} load={()=>children.fetchNextPage()} label="Load more tasks"/></div>}</article>
}
function GroupProgressBar({group}:{group:JobGroup}){const terminal=group.progress.successful+group.progress.failed+group.progress.cancelled;if(!terminal)return <div className="progress-track"><span className={group.progress.percent===null?'indeterminate':''} style={group.progress.percent===null?undefined:{width:`${group.progress.percent}%`}}/></div>;const total=group.progress.total||terminal;return <div className="progress-track segmented" aria-label={`${group.progress.successful} succeeded, ${group.progress.failed} failed, ${group.progress.cancelled} cancelled`}><span className="success" style={{width:`${group.progress.successful*100/total}%`}}/><span className="failure" style={{width:`${group.progress.failed*100/total}%`}}/><span className="cancelled" style={{width:`${group.progress.cancelled*100/total}%`}}/></div>}
function JobProgress({job}:{job:Job}){if(job.progress.percent===null&&!job.progress.message)return null;return <div className="job-progress"><div><span>{job.progress.message||job.progress.phase}</span><b>{job.progress.percent===null?'Working…':`${job.progress.percent}%`}</b></div><div className="progress-track"><span className={job.progress.percent===null?'indeterminate':''} style={job.progress.percent===null?undefined:{width:`${job.progress.percent}%`}}/></div></div>}
function JobCard({job}:{job:Job}){const [open,setOpen]=useState(false);const bad=job.status==='failed';return <article className={`job-card ${bad?'bad':''}`}><div className="job-head"><div className="job-kind-icon">{job.kind==='source_pull'?<RefreshCw/>:job.kind==='chapter_download'?<Download/>:job.kind==='maintenance'?<Activity/>:<Settings/>}</div><div><h3>{job.description}</h3><span>#{job.id} · {job.pool}</span></div><StatusPill value={job.status}/></div>{job.context.cover_url&&<div className="job-context"><img src={job.context.cover_url}/><span>{job.context.title}</span></div>}<JobProgress job={job}/><div className="job-meta"><span>Attempt {job.attempt}/{job.max_attempts}</span>{job.queue_position&&<span>Queue position {job.queue_position}</span>}<span>{job.status==='retry_wait'?`Available ${relativeTime(job.available_at)}`:`Updated ${relativeTime(job.updated_at)}`}</span></div>{job.error_message&&<><button className="details-toggle" onClick={()=>setOpen(!open)}>{open?<ChevronDown/>:<ChevronRight/>}Error details</button>{open&&<div className="error-box"><code>{job.error_message}</code><button onClick={()=>navigator.clipboard.writeText(job.error_message)}>Copy</button></div>}</>}</article>}
function JobTable({jobs}:{jobs:Job[]}){const client=useQueryClient(),toast=useContext(ToastContext);const retry=useMutation({mutationFn:api.retryJob,onSuccess:()=>{client.invalidateQueries({queryKey:['jobs']});toast({message:'Job queued for retry'})}});return <div className="job-table">{jobs.map(job=><div className="job-table-row" key={job.id}><div className="job-table-main"><b>{job.description}</b><span>#{job.id} · {job.pool}{job.source?` · ${job.source}`:''}</span><JobProgress job={job}/></div><StatusPill value={job.status}/><span>{relativeTime(job.updated_at)}</span><span className="job-error" title={job.error_message}>{job.error_message||'—'}</span>{['failed','cancelled'].includes(job.status)?<button className="secondary" onClick={()=>retry.mutate(job.id)}><RefreshCw/>Retry</button>:<span/>}</div>)}</div>}

function groupEvents(events:ActivityEvent[]){const result:{event:ActivityEvent;count:number}[]=[];const groups=new Map<string,{event:ActivityEvent;count:number}>();for(const event of events){const key=[event.job.kind,event.job.source,event.type,event.status,event.message].join('|');const existing=groups.get(key);if(existing)existing.count++;else{const group={event,count:1};groups.set(key,group);result.push(group)}}return result}
function humanEvent(type:string){return ({enqueued:'Added to the queue',leased:'Worker started the job',succeeded:'Completed successfully',retry_scheduled:'Will retry after a delay',failed:'The operation failed',released:'Returned to the queue'} as Record<string,string>)[type]||type.replaceAll('_',' ')}
function relativeTime(value:string){const seconds=Math.round((new Date(value).getTime()-Date.now())/1000);const abs=Math.abs(seconds);if(abs<60)return seconds>0?'in a moment':'just now';const units:Array<[number,Intl.RelativeTimeFormatUnit]>=[[31536000,'year'],[2592000,'month'],[86400,'day'],[3600,'hour'],[60,'minute']];const [size,unit]=units.find(([size])=>abs>=size)!;return new Intl.RelativeTimeFormat(undefined,{numeric:'auto'}).format(Math.round(seconds/size),unit)}
function formatDate(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
