export type Source = {name:string;title:string;url:string}
export type Series = {id:number;title:string;description:string;cover_url:string;status:string;integrity_state:string;latest_chapter:string;latest_source:string;latest_at:string|null;sources:Source[];aliases:string[];chapter_count:number;read_count:number;unread_count:number}
export type Chapter = {id:number;number:string;title:string;source:string;url:string;released_at:string;reading_status:string}
export type UpdateSeries = Series & {unread_chapters:Chapter[]}
export type Page<T,C=string> = {items:T[];next_cursor:C|null}
export type Job = {id:number;kind:string;description:string;source:string;pool:string;cycle_id:number|null;workflow_key:string;group_key:string;status:string;queue_position:number|null;attempt:number;max_attempts:number;error_code:string;error_message:string;available_at:string;created_at:string;updated_at:string;completed_at:string|null;progress:{phase:string;current:number;total:number;unit:string;bytes:number;message:string;updated_at:string|null;percent:number|null};context:{series_id?:number;title?:string;cover_url?:string;chapter?:string}}
export type JobGroup = {key:string;kind:string;source:string;title:string;cover_url:string;task_count:number;status_counts:Record<string,number>;progress:{current:number;total:number;percent:number|null;successful:number;failed:number;cancelled:number};representative:Job;single:boolean}
export type WorkloadCycle = {id:number|null;status:string;total:number;successful:number;failed:number;cancelled:number;superseded:number;remaining:number;added:number;started_at?:string;updated_at?:string}
export type MatchSide = Series & {source_title:string;source:string;url:string}
export type Match = {id:number;decision_ids:number[];confidence:number;evidence:{tone:string;label:string}[];blocked_reasons:string[];left:MatchSide;right:MatchSide}
export type ScoreBreakdown = {score:number;title:number;cover:number;description:number;chapter_overlap:number;matched_selected_id?:number}
export type MergeCandidate = Series & {similarity:number;compatible:boolean;conflicting_sources:string[];score_breakdown:ScoreBreakdown}
export type MergePreview = {target_id:number;target_title:string;items:Series[];conflicting_sources:string[];can_merge:boolean}
export type ActivityEvent = {id:number;job:Job;type:string;status:string;message:string;details:Record<string,unknown>;created_at:string}
export type Operations = {job_counts:Record<string,number>;active_groups:number;health:Record<string,number>;sources:{source:string;status:string;failures:number;last_error:string;last_poll_at:string|null;cooldown_until:string|null;enabled:boolean;frontier_metrics:Record<string,number|boolean>}[];workers:{id:string;status:string;active_job_id:number|null;heartbeat_at:string;metadata:Record<string,unknown>}[];permits:Record<string,number>;provider_policies:{source:string;job_limit:number;page_limit:number;request_interval_seconds:number;cooldown_seconds:number;poll_interval_seconds:number;clean_since:string|null;last_limited_at:string|null;next_exploration_at:string|null}[];provider_endpoints:{source:string;traffic_class:string;request_interval_seconds:number;failures:number;cooldown_until:string|null;last_error:string}[];recent_benchmarks:{id:number;source:string;state:string;tier:number;requests:number;failures:number;signal:string}[]}
